export const footerSections = [
	{
		title: "Get to Know Us",
		links: [
			{ text: "Amazon Newsletter", url: "#" },
			{ text: "career", url: "https://www.amazon.jobs/en/" },
			{ text: "About Amazon", url: "#" },
			{ text: "Accessibility", url: "#" },
			{ text: "Sustainability", url: "#" },
			{ text: "Accessibility", url: "#" },
			{ text: "Press Center", url: "#" },
			{ text: "Investor Relations", url: "#" },
			{ text: "Amazon Devices", url: "#" },
			{ text: "Amazon Science", url: "#" },
		],
	},
	{
		title: "Make Money with Us",
		links: [
			{ text: "Sell on Amazon", url: "#" },
			{ text: "Sell apps on Amazon", url: "#" },
			{ text: "Supply to Amazon", url: "#" },
			{ text: "Protect & Build Your Brand", url: "#" },
			{ text: "Become an Affiliate", url: "#" },
			{ text: "Become a Delivery Driver", url: "#" },
			{ text: "Start a Package Delivery Business", url: "#" },
			{ text: "Advertise Your Products", url: "#" },
			{ text: "Self-Publish with Us", url: "#" },
			{ text: "Become an Amazon Hub Partner", url: "#" },
			{ text: "›See More Ways to Make Money", url: "#" },
		],
	},
	{
		title: "Amazon Payment Products",
		links: [
			{ text: "Amazon Visa", url: "#" },
			{ text: "Amazon Store Card", url: "#" },
			{ text: "Shop with Points", url: "#" },
			{ text: "Amazon Secured Card", url: "#" },
			{ text: "Amazon Business Card", url: "#" },
			{ text: "Credit Card Marketplace", url: "#" },
			{ text: "Reload Your Balance", url: "#" },
			{ text: "Gift Cards", url: "#" },
			{ text: "Amazon Currency Converter", url: "#" },
		],
	},
	{
		title: "Let Us Help You",
		links: [
			{ text: "Your Account", url: "#" },
			{ text: "Shipping Rates & Policies", url: "#" },
			{ text: "Help", url: "#" },
			{ text: "Your Orders", url: "#" },
			{ text: "Amazon Prime", url: "#" },
			{ text: "Returns & Replacements", url: "#" },
			{ text: " Manage Your Content and Devices", url: "#" },
			{ text: "Recalls and Product Safety Alerts", url: "#" },
		],
	},
];
